---
platform: linux

params:
  GOOS: darwin
  GOARCH:
  OUTPUT_FILE:

inputs:
- name: concourse-up-whole-repo
- name: version

outputs:
- name: build-darwin

run:
  path: concourse-up/ci/tasks/build.sh
