---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
- name: concourse-up

run:
  path: concourse-up/ci/tasks/cleanup-tests.sh

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  VERBOSE:
