#!/bin/bash

[ "$VERBOSE" ] && { set -x; export BOSH_LOG_LEVEL=debug; }
set -eu
set -x

deployment="system-test-$RANDOM"
cleanup() {
  status=$?
  ./cup --non-interactive destroy $deployment
  exit $status
}
set +u
if [ -z "$SKIP_TEARDOWN" ]; then
  trap cleanup EXIT
else
  trap "echo Skipping teardown" EXIT
fi
set -u

cp "$BINARY_PATH" ./cup
chmod +x ./cup

echo "DEPLOY WITH AUTOGENERATED CERT, NO DOMAIN, CUSTOM REGION, DEFAULT WORKERS"

./cup deploy $deployment

sleep 60

config=$(./cup info --json $deployment)
domain=$(echo "$config" | jq -r '.config.domain')
username=$(echo "$config" | jq -r '.config.concourse_username')
password=$(echo "$config" | jq -r '.config.concourse_password')
echo "$config" | jq -r '.config.concourse_ca_cert' > generated-ca-cert.pem

eval "$(./cup info --env $deployment)"
credhub api
credhub set -n /concourse/main/password -t password -w c1oudc0w

fly --target system-test login \
  --ca-cert generated-ca-cert.pem \
  --concourse-url "https://$domain" \
  --username "$username" \
  --password "$password"

fly --target system-test sync

fly --target system-test set-pipeline \
  --non-interactive \
  --pipeline credhub \
  --config "$(dirname "$0")/credhub.yml"

fly --target system-test unpause-pipeline \
    --pipeline credhub

fly --target system-test trigger-job \
  --job credhub/credhub \
  --watch
