#!/bin/bash

set -eu

mkdir -p $GOPATH/src/github.com/engineerbetter/concourse-up
mv concourse-up/* $GOPATH/src/github.com/engineerbetter/concourse-up
cd $GOPATH/src/github.com/engineerbetter/concourse-up

deployment="system-test-$RANDOM"

# DEPLOY WITH AUTOGENERATED CERT, NO DOMAIN

go run main.go deploy $deployment

config=$(go run main.go info $deployment)
domain=$(echo $config | jq -r '.config.domain')
username=$(echo $config | jq -r '.config.concourse_username')
password=$(echo $config | jq -r '.config.concourse_password')
echo $config | jq -r '.config.concourse_ca_cert' > generated-ca-cert.pem

fly --target system-test login \
  --ca-cert generated-ca-cert.pem \
  --concourse-url https://$domain \
  --username $username \
  --password $password

set -x
fly --target system-test workers
set +x

# DEPLOY WITH AUTOGENERATED CERT, AND CUSTOM DOMAIN

custom_domain="$deployment-auto-2.concourse-up.engineerbetter.com"

go run main.go deploy $deployment --domain $custom_domain

sleep 60

config=$(go run main.go info $deployment)
username=$(echo $config | jq -r '.config.concourse_username')
password=$(echo $config | jq -r '.config.concourse_password')
echo $config | jq -r '.config.concourse_ca_cert' > generated-ca-cert.pem

fly --target system-test-custom-domain login \
  --ca-cert generated-ca-cert.pem \
  --concourse-url https://$custom_domain \
  --username $username \
  --password $password

set -x
fly --target system-test-custom-domain workers
set +x

# DEPLOY WITH USER PROVIDED CERT

custom_domain="$deployment-user.concourse-up.engineerbetter.com"

certstrap init \
  --common-name "$deployment" \
  --passphrase "" \
  --organization "" \
  --organizational-unit "" \
  --country "" \
  --province "" \
  --locality ""

certstrap request-cert \
   --passphrase "" \
   --domain $custom_domain

certstrap sign "$custom_domain" --CA "$deployment"

go run main.go deploy $deployment \
  --domain $custom_domain \
  --tls-cert "$(cat out/$custom_domain.crt)" \
  --tls-key "$(cat out/$custom_domain.key)"

sleep 60

config=$(go run main.go info $deployment)
username=$(echo $config | jq -r '.config.concourse_username')
password=$(echo $config | jq -r '.config.concourse_password')
echo $config | jq -r '.config.concourse_ca_cert' > generated-ca-cert.pem

fly --target system-test-custom-domain-with-cert login \
  --ca-cert out/$deployment.crt \
  --concourse-url https://$custom_domain \
  --username $username \
  --password $password

set -x
fly --target system-test-custom-domain-with-cert workers
set +x

# DESTROY

go run main.go --non-interactive destroy $deployment