---
platform: linux

inputs:
- name: concourse-up
- name: concourse-up-ops

run:
  path: concourse-up/ci/tasks/unit-test.sh

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
