package config

// Config represents a concourse-up configuration file
type Config struct {
	AllowIPs                  string   `json:"allow_ips"`
	AvailabilityZone          string   `json:"availability_zone"`
	ConcourseCACert           string   `json:"concourse_ca_cert"`
	ConcourseCert             string   `json:"concourse_cert"`
	ConcourseKey              string   `json:"concourse_key"`
	ConcoursePassword         string   `json:"concourse_password"`
	ConcourseUsername         string   `json:"concourse_username"`
	ConcourseUserProvidedCert bool     `json:"concourse_user_provided_cert"`
	ConcourseWebSize          string   `json:"concourse_web_size"`
	ConcourseWorkerCount      int      `json:"concourse_worker_count"`
	ConcourseWorkerSize       string   `json:"concourse_worker_size"`
	ConfigBucket              string   `json:"config_bucket"`
	CredhubAdminClientSecret  string   `json:"credhub_admin_client_secret"`
	CredhubCACert             string   `json:"credhub_ca_cert"`
	CredhubPassword           string   `json:"credhub_password"`
	CredhubURL                string   `json:"credhub_url"`
	CredhubUsername           string   `json:"credhub_username"`
	Deployment                string   `json:"deployment"`
	DirectorCACert            string   `json:"director_ca_cert"`
	DirectorCert              string   `json:"director_cert"`
	DirectorHMUserPassword    string   `json:"director_hm_user_password"`
	DirectorKey               string   `json:"director_key"`
	DirectorMbusPassword      string   `json:"director_mbus_password"`
	DirectorNATSPassword      string   `json:"director_nats_password"`
	DirectorPassword          string   `json:"director_password"`
	DirectorPublicIP          string   `json:"director_public_ip"`
	DirectorRegistryPassword  string   `json:"director_registry_password"`
	DirectorUsername          string   `json:"director_username"`
	Domain                    string   `json:"domain"`
	EncryptionKey             string   `json:"encryption_key"`
	GithubAuthIsSet           bool     `json:"github_auth_is_set"`
	GithubClientID            string   `json:"github_client_id"`
	GithubClientSecret        string   `json:"github_client_secret"`
	GrafanaPassword           string   `json:"grafana_password"`
	HostedZoneID              string   `json:"hosted_zone_id"`
	HostedZoneRecordPrefix    string   `json:"hosted_zone_record_prefix"`
	IAAS                      string   `json:"iaas"`
	Namespace                 string   `json:"namespace"`
	PrivateKey                string   `json:"private_key"`
	Project                   string   `json:"project"`
	PublicKey                 string   `json:"public_key"`
	RDSDefaultDatabaseName    string   `json:"rds_default_database_name"`
	RDSInstanceClass          string   `json:"rds_instance_class"`
	RDSPassword               string   `json:"rds_password"`
	RDSUsername               string   `json:"rds_username"`
	Region                    string   `json:"region"`
	SourceAccessIP            string   `json:"source_access_ip"`
	Spot                      bool     `json:"spot"`
	Tags                      []string `json:"tags"`
	TFStatePath               string   `json:"tf_state_path"`
	Version                   string   `json:"version"`
	WorkerType                string   `json:"worker_type"`
	PrivateCIDR               string   `json:"private_cidr"`
	PublicCIDR                string   `json:"public_cidr"`
	NetworkCIDR               string   `json:"network_cidr"`
	RDS1CIDR                  string   `json:"rds1_cidr"`
	RDS2CIDR                  string   `json:"rds2_cidr"`
}
