---
groups:
- name: Main
  jobs:
  - set-pipeline
  - unit-tests
  - build
  - smoke-test
  - system-test
  - system-test-update
  - system-test-m5
  - system-test-letsencrypt
  - system-test-options-and-destroy
  - system-test-options-and-destroy-gcp
  - smoke-test-gcp
  - system-test-gcp
  - auto
  - major
  - minor
  - patch
- name: Notifications
  jobs:
  - detect-versions
- name: Cleanup
  jobs:
  - cleanup

resource_types:
- name: pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: build-metadata
  type: docker-image
  source:
    repository: mastertinner/build-metadata-resource

- name: bosh-io-release
  type: docker-image
  source:
    repository: engineerbetter/bosh-io-release-resource

resources:
- name: this-pipeline
  type: pipeline
  source:
    target: https://ci.engineerbetter.com
    insecure: "true"
    teams:
    - name: main
      username: admin
      password: ((atc_main_password))

- name: concourse-up
  type: git
  source:
    uri: git@github.com:EngineerBetter/concourse-up.git
    branch: master
    private_key: ((github_private_key))
    ignore_paths:
    - README.md

- name: concourse-up-ops
  type: git
  source:
    uri: git@github.com:EngineerBetter/concourse-up-ops.git
    branch: master
    tag_filter: 0.*.*
    private_key: ((github_private_key))
    ignore_paths:
    - README.md

- name: pcf-ops
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    username: ((dockerhub_user))
    password: ((dockerhub_password))

- name: version
  type: semver
  source:
    initial_version: 0.0.0
    driver: s3
    bucket: concourse-up-ci-artifacts
    key: version
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))
    region_name: eu-west-1

- name: binary-linux
  type: s3
  source:
    bucket: concourse-up-ci-artifacts
    versioned_file: concourse-up-linux-amd64
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))
    region_name: eu-west-1

- name: binary-darwin
  type: s3
  source:
    bucket: concourse-up-ci-artifacts
    versioned_file: concourse-up-darwin-amd64
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))
    region_name: eu-west-1

- name: binary-windows
  type: s3
  source:
    bucket: concourse-up-ci-artifacts
    versioned_file: concourse-up-darwin-amd64
    access_key_id: ((concourse_ci_s3_access_key))
    secret_access_key: ((concourse_ci_s3_secret_key))
    region_name: eu-west-1

- name: release
  type: github-release
  source:
    user: engineerbetter
    repository: concourse-up
    access_token: ((github_access_token))

- name: release-drafts
  type: github-release
  source:
    user: engineerbetter
    repository: concourse-up
    access_token: ((github_access_token))
    drafts: true

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack_webhook))

- name: cup-slack-alert
  type: slack-notification
  source:
    url: ((cup_slack_webhook))

- name: once-daily
  type: time
  source: {interval: 24h}

- name: build-metadata
  type: build-metadata

jobs:
- name: set-pipeline
  plan:
  - get: concourse-up
    trigger: true
  - put: this-pipeline
    params:
      pipelines:
      - name: concourse-up
        team: main
        config_file: concourse-up/ci/pipeline.yml

- name: unit-tests
  plan:
  - aggregate:
    - get: pcf-ops
    - get: concourse-up
      trigger: true
      passed: [set-pipeline]
    - get: concourse-up-ops
      trigger: true
  - task: lint
    image: pcf-ops
    file: concourse-up/ci/tasks/lint.yml
    on_failure:
      put: slack-alert
      params:
        channel: "#integrations"
        text: |
          <!channel> Concourse Up lint failure!
  - task: unit-test
    image: pcf-ops
    file: concourse-up/ci/tasks/unit-test.yml
    params:
      AWS_ACCESS_KEY_ID: ((concourse_up_test_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((concourse_up_test_secret_key))
      AWS_DEFAULT_REGION: ((aws_default_region))
    on_failure:
      put: slack-alert
      params:
        channel: "#integrations"
        text: |
          <!channel> Concourse Up unit tests failure!

- name: build
  plan:
  - aggregate:
    - get: pcf-ops
      passed: [unit-tests]
    - get: concourse-up
      trigger: true
      passed: [unit-tests]
    - get: concourse-up-ops
      trigger: true
      passed: [unit-tests]
    - get: version
  - aggregate:
    - do:
      - task: build-linux
        image: pcf-ops
        params:
          GOOS: linux
          GOARCH: amd64
          OUTPUT_FILE: concourse-up-linux-amd64
        file: concourse-up/ci/tasks/build_linux.yml
      - put: binary-linux
        params:
          file: build-linux/concourse-up-linux-amd64
    - do:
      - task: build-darwin
        image: pcf-ops
        params:
          GOOS: darwin
          GOARCH: amd64
          OUTPUT_FILE: concourse-up-darwin-amd64
        file: concourse-up/ci/tasks/build_darwin.yml
      - put: binary-darwin
        params:
          file: build-darwin/concourse-up-darwin-amd64
    - do:
      - task: build-windows
        image: pcf-ops
        params:
          GOOS: windows
          GOARCH: amd64
          OUTPUT_FILE: concourse-up-windows-amd64.exe
        file: concourse-up/ci/tasks/build_windows.yml
      - put: binary-windows
        params:
          file: build-windows/concourse-up-windows-amd64.exe

- name: smoke-test
  serial_groups:
  - smoke-test
  serial: true
  plan:
  - aggregate: &smoke-test-gets
    - get: version
      passed: [build]
    - get: binary-linux
      trigger: true
      passed: [build]
    - get: binary-darwin
      trigger: true
      passed: [build]
    - get: binary-windows
      trigger: true
      passed: [build]
    - get: concourse-up
      trigger: true
      passed: [build]
    - get: concourse-up-ops
      trigger: true
      passed: [build]
    - get: pcf-ops
      passed: [build]
    - get: release
      params:
        globs: [concourse-up-linux-amd64]
  - task: smoke-test
    file: concourse-up/ci/tasks/smoke-test.yml
    params:
      AWS_ACCESS_KEY_ID: ((concourse_up_test_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((concourse_up_test_secret_key))
      BINARY_PATH: binary-linux/concourse-up-linux-amd64
    on_failure:
      put: slack-alert
      params:
        channel: "#integrations"
        text: |
          <!channel> Concourse Up smoke test failure!

- name: smoke-test-gcp
  serial_groups:
  - smoke-test-gcp
  serial: true
  plan:
  - aggregate: *smoke-test-gets
  - task: smoke-test
    file: concourse-up/ci/tasks/smoke-test.yml
    params:
      BINARY_PATH: binary-linux/concourse-up-linux-amd64
      GOOGLE_APPLICATION_CREDENTIALS_CONTENTS: ((system_test_google_application_credentials))
      IAAS: GCP
    on_failure:
      put: slack-alert
      params:
        channel: "#integrations"
        text: |
          <!channel> Concourse Up GCP smoke test failure!

- name: system-test
  serial_groups:
  - system-test
  serial: true
  plan:
  - aggregate: &system-test-gets
    - get: version
      passed: [smoke-test]
    - get: binary-linux
      trigger: true
      passed: [smoke-test]
    - get: binary-darwin
      trigger: true
      passed: [smoke-test]
    - get: binary-windows
      trigger: true
      passed: [smoke-test]
    - get: concourse-up
      trigger: true
      passed: [smoke-test]
    - get: concourse-up-ops
      trigger: true
      passed: [smoke-test]
    - get: pcf-ops
      passed: [smoke-test]
    - get: release
      params:
        globs: [concourse-up-linux-amd64]
  - task: system-test
    file: concourse-up/ci/tasks/system-test.yml
    params:
      AWS_ACCESS_KEY_ID: ((concourse_up_test_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((concourse_up_test_secret_key))
      BINARY_PATH: binary-linux/concourse-up-linux-amd64
    on_failure:
      put: slack-alert
      params:
        channel: "#integrations"
        text: |
          <!channel> Concourse Up system test failure!

- name: system-test-gcp
  serial_groups:
  - system-test-gcp
  serial: true
  plan:
  - aggregate: &system-test-gets-gcp
    - get: version
      passed: [smoke-test-gcp]
    - get: binary-linux
      trigger: true
      passed: [smoke-test-gcp]
    - get: binary-darwin
      trigger: true
      passed: [smoke-test-gcp]
    - get: binary-windows
      trigger: true
      passed: [smoke-test-gcp]
    - get: concourse-up
      trigger: true
      passed: [smoke-test-gcp]
    - get: concourse-up-ops
      trigger: true
      passed: [smoke-test-gcp]
    - get: pcf-ops
      passed: [smoke-test-gcp]
    - get: release
      params:
        globs: [concourse-up-linux-amd64]
  - task: system-test
    file: concourse-up/ci/tasks/system-test.yml
    params:
      GOOGLE_APPLICATION_CREDENTIALS_CONTENTS: ((system_test_google_application_credentials))
      IAAS: GCP
      BINARY_PATH: binary-linux/concourse-up-linux-amd64
      on_failure:
        put: slack-alert
        params:
          channel: "#integrations"
          text: |
            <!channel> Concourse Up GCP system test failure!

- name: system-test-update
  serial_groups:
  - system-test-update
  serial: true
  plan:
  - aggregate: *system-test-gets
  - task: run-system-test-update
    file: concourse-up/ci/tasks/system-test-update.yml
    params:
      AWS_ACCESS_KEY_ID: ((concourse_up_test_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((concourse_up_test_secret_key))
      BINARY_PATH: binary-linux/concourse-up-linux-amd64
      on_failure:
        put: slack-alert
        params:
          channel: "#integrations"
          text: |
            <!channel> Concourse Up update system test failure!

- name: system-test-m5
  serial_groups:
  - system-test-m5
  serial: true
  plan:
  - aggregate: *system-test-gets
  - task: system-test-m5
    file: concourse-up/ci/tasks/system-test-m5.yml
    params:
      AWS_ACCESS_KEY_ID: ((concourse_up_test_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((concourse_up_test_secret_key))
      BINARY_PATH: binary-linux/concourse-up-linux-amd64
    on_failure:
      put: slack-alert
      params:
        channel: "#integrations"
        text: |
          <!channel> Concourse Up m5 system test failure!

- name: system-test-letsencrypt
  serial_groups:
  - system-test-letencrypt
  serial: true
  plan:
  - aggregate: *system-test-gets
  - task: system-test-letsencrypt
    file: concourse-up/ci/tasks/system-test-autocert.yml
    params:
      AWS_ACCESS_KEY_ID: ((concourse_up_test_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((concourse_up_test_secret_key))
      BINARY_PATH: binary-linux/concourse-up-linux-amd64
    on_failure:
      put: slack-alert
      params:
        channel: "#integrations"
        text: |
          <!channel> Concourse Up system letsencrypt test failure!

- name: system-test-options-and-destroy
  serial_groups:
  - system-test-options-and-destroy
  serial: true
  plan:
  - aggregate: *system-test-gets
  - task: system-test-options-and-destroy
    file: concourse-up/ci/tasks/system-test-options-and-destroy.yml
    params:
      IAAS: AWS
      AWS_ACCESS_KEY_ID: ((concourse_up_test_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((concourse_up_test_secret_key))
      BINARY_PATH: binary-linux/concourse-up-linux-amd64
      EB_WILDCARD_CERT: ((eb_wildcard.certificate))
      EB_WILDCARD_KEY: ((eb_wildcard.private_key))
      GITHUB_AUTH_CLIENT_ID: ((github_auth_client_id))
      GITHUB_AUTH_CLIENT_SECRET: ((github_auth_client_secret))
    on_failure:
      put: slack-alert
      params:
        channel: "#integrations"
        text: |
          <!channel> Concourse Up system-test-options-and-destroy failure!
- name: system-test-options-and-destroy-gcp
  serial_groups:
  - system-test-options-and-destroy-gcp
  serial: true
  plan:
  - aggregate: *system-test-gets-gcp
  - task: system-test-options-and-destroy
    file: concourse-up/ci/tasks/system-test-options-and-destroy.yml
    params:
      GOOGLE_APPLICATION_CREDENTIALS_CONTENTS: ((system_test_google_application_credentials))
      IAAS: GCP
      BINARY_PATH: binary-linux/concourse-up-linux-amd64
      EB_WILDCARD_CERT: ((eb_wildcard.certificate))
      EB_WILDCARD_KEY: ((eb_wildcard.private_key))
      GITHUB_AUTH_CLIENT_ID: ((github_auth_client_id))
      GITHUB_AUTH_CLIENT_SECRET: ((github_auth_client_secret))
    on_failure:
      put: slack-alert
      params:
        channel: "#integrations"
        text: |
          <!channel> Concourse Up system-test-options-and-destroy-gcp failure!

- name: auto
  serial: true
  plan:
  - aggregate:
    - get: pcf-ops
      passed: &aws-system-tests
      - system-test
      - system-test-update
      - system-test-m5
      - system-test-letsencrypt
      - system-test-options-and-destroy
    - get: concourse-up
      passed: *aws-system-tests
    - get: concourse-up-ops
      trigger: true
      passed: *aws-system-tests
    - get: version
      passed: *aws-system-tests
      params:
        bump: patch
    - get: build-metadata
  - aggregate: &build_binaries
    - task: build-linux
      image: pcf-ops
      params:
        GOARCH: amd64
        OUTPUT_FILE: concourse-up-linux-amd64
      file: concourse-up/ci/tasks/build_linux_from_version_file.yml
    - task: build-darwin
      image: pcf-ops
      params:
        GOARCH: amd64
        OUTPUT_FILE: concourse-up-darwin-amd64
      file: concourse-up/ci/tasks/build_darwin_from_version_file.yml
    - task: build-windows
      image: pcf-ops
      params:
        GOARCH: amd64
        OUTPUT_FILE: concourse-up-windows-amd64.exe
      file: concourse-up/ci/tasks/build_windows_from_version_file.yml
  - task: get-ops-version
    image: pcf-ops
    file: concourse-up/ci/tasks/get-ops-version.yml
    params:
      CONCOURSE_PASSWORD: ((ebci_password))
      CONCOURSE_URL: https://ci.engineerbetter.com
  - task: write-release-vars
    image: pcf-ops
    file: concourse-up/ci/tasks/write-release-vars.yml
  - put: release
    params:
      name: release-vars/name
      commitish: release-vars/commit
      body: release-vars/body
      tag: version/version
      globs:
      - build-linux/concourse-up-linux-amd64
      - build-darwin/concourse-up-darwin-amd64
      - build-windows/concourse-up-windows-amd64.exe
  - put: version
    resource: version
    params:
      file: version/version
  - put: slack-alert
    params:
      channel: "#integrations"
      text_file: release-vars/slackmsg

- name: patch
  serial: true
  plan:
  - aggregate:
    - get: version
      params:
        bump: patch
      passed: *aws-system-tests
    - get: pcf-ops
      passed: *aws-system-tests
    - get: concourse-up
      passed: *aws-system-tests
    - get: concourse-up-ops
      passed: *aws-system-tests
    - get: build-metadata
  - aggregate: *build_binaries
  - task: get-ops-version
    image: pcf-ops
    file: concourse-up/ci/tasks/get-ops-version.yml
    params:
      CONCOURSE_PASSWORD: ((ebci_password))
      CONCOURSE_URL: https://ci.engineerbetter.com
  - task: write-release-vars
    image: pcf-ops
    file: concourse-up/ci/tasks/write-release-vars.yml
  - put: release-drafts
    params:
      name: release-vars/name
      commitish: release-vars/commit
      body: release-vars/body
      tag: version/version
      globs:
      - build-linux/concourse-up-linux-amd64
      - build-darwin/concourse-up-darwin-amd64
      - build-windows/concourse-up-windows-amd64.exe
  - put: version
    resource: version
    params:
      file: version/version
  - put: slack-alert
    params:
      channel: "#integrations"
      text_file: release-vars/slackmsg

- name: minor
  serial: true
  plan:
  - aggregate:
    - get: version
      params:
        bump: minor
      passed: *aws-system-tests
    - get: pcf-ops
      passed: *aws-system-tests
    - get: concourse-up
      passed: *aws-system-tests
    - get: concourse-up-ops
      passed: *aws-system-tests
    - get: build-metadata
  - aggregate: *build_binaries
  - task: get-ops-version
    image: pcf-ops
    file: concourse-up/ci/tasks/get-ops-version.yml
    params:
      CONCOURSE_PASSWORD: ((ebci_password))
      CONCOURSE_URL: https://ci.engineerbetter.com
  - task: write-release-vars
    image: pcf-ops
    file: concourse-up/ci/tasks/write-release-vars.yml
  - put: release-drafts
    params:
      name: release-vars/name
      commitish: release-vars/commit
      body: release-vars/body
      tag: version/version
      globs:
      - build-linux/concourse-up-linux-amd64
      - build-darwin/concourse-up-darwin-amd64
      - build-windows/concourse-up-windows-amd64.exe
  - put: version
    resource: version
    params:
      file: version/version
  - put: slack-alert
    params:
      channel: "#integrations"
      text_file: release-vars/slackmsg

- name: major
  serial: true
  plan:
  - aggregate:
    - get: version
      passed: *aws-system-tests
      params:
        bump: major
    - get: pcf-ops
      passed: *aws-system-tests
    - get: concourse-up
      passed: *aws-system-tests
    - get: concourse-up-ops
      passed: *aws-system-tests
    - get: build-metadata
  - aggregate: *build_binaries
  - task: get-ops-version
    image: pcf-ops
    file: concourse-up/ci/tasks/get-ops-version.yml
    params:
      CONCOURSE_PASSWORD: ((ebci_password))
      CONCOURSE_URL: https://ci.engineerbetter.com
  - task: write-release-vars
    image: pcf-ops
    file: concourse-up/ci/tasks/write-release-vars.yml
  - put: release-drafts
    params:
      name: release-vars/name
      commitish: release-vars/commit
      body: release-vars/body
      tag: version/version
      globs:
      - build-linux/concourse-up-linux-amd64
      - build-darwin/concourse-up-darwin-amd64
      - build-windows/concourse-up-windows-amd64.exe
  - put: version
    resource: version
    params:
      file: version/version
  - put: slack-alert
    params:
      channel: "#integrations"
      text_file: release-vars/slackmsg

- name: detect-versions
  serial_groups: [deployment]
  serial: true
  plan:
  - aggregate:
    - get: release
      trigger: true
    - get: concourse-up
    - get: pcf-ops
  - task: detect-majors
    image: pcf-ops
    config:
      platform: linux
      inputs:
      - name: release
      - name: concourse-up
      outputs:
      - name: output
      run:
        path: bash
        args:
          - -xeuc
          - |
            touch output/message
            concourse-up/ci/tasks/get-versions.rb > output/message
  - put: slack-alert
    params:
      channel: "#integrations"
      text: |
        $TEXT_FILE_CONTENT
      text_file: output/message
  - put: cup-slack-alert
    params:
      channel: ((cup_slack_channel))
      text: |
        $TEXT_FILE_CONTENT
      text_file: output/message

- name: cleanup
  serial: true
  serial_groups:
  - system-test
  - system-test-update
  - system-test-m5
  - system-test-letsencrypt
  - system-test-options-and-destroy
  plan:
  - aggregate:
    - get: concourse-up
    - get: once-daily
      trigger: true
    - get: binary-linux
  - task: cleanup
    file: concourse-up/ci/tasks/cleanup-tests.yml
    params:
      AWS_ACCESS_KEY_ID: ((concourse_up_test_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((concourse_up_test_secret_key))
    on_failure:
      put: slack-alert
      params:
        channel: "#integrations"
        text: |
          Concourse-Up cleanup failure!
