---
azs:
- name: z1
  cloud_properties:
    availability_zone: <% .AvailabilityZone %>

vm_types:
- name: concourse-web-small
  cloud_properties:
    instance_type: t2.small
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>

- name: concourse-web-medium
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>

- name: concourse-web-large
  cloud_properties:
    instance_type: t2.large
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>

- name: concourse-web-xlarge
  cloud_properties:
    instance_type: t2.xlarge
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>

- name: concourse-web-2xlarge
  cloud_properties:
    instance_type: t2.2xlarge
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>

- name: concourse-medium
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>
    iam_instance_profile:
    - <% .VMsInstanceProfile %>

- name: concourse-large
  cloud_properties:
    instance_type: m4.large
    spot_bid_price: 0.13 # on-demand price: 0.111
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>
    iam_instance_profile:
    - <% .VMsInstanceProfile %>

- name: concourse-xlarge
  cloud_properties:
    instance_type: m4.xlarge
    spot_bid_price: 0.27 # on-demand price: 0.222
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>
    iam_instance_profile:
    - <% .VMsInstanceProfile %>

- name: concourse-2xlarge
  cloud_properties:
    instance_type: m4.2xlarge
    spot_bid_price: 0.53 # on-demand price: 0.444
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>
    iam_instance_profile:
    - <% .VMsInstanceProfile %>

- name: concourse-4xlarge
  cloud_properties:
    instance_type: m4.4xlarge
    spot_bid_price: 1.07 # on-demand price: 0.888
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>
    iam_instance_profile:
    - <% .VMsInstanceProfile %>

- name: concourse-10xlarge
  cloud_properties:
    instance_type: m4.10xlarge
    spot_bid_price: 2.67 # on-demand price: 2.22
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>
    iam_instance_profile:
    - <% .VMsInstanceProfile %>

- name: concourse-16xlarge
  cloud_properties:
    instance_type: m4.16xlarge
    spot_bid_price: 4.26 # on-demand price: 3.55
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>
    iam_instance_profile:
    - <% .VMsInstanceProfile %>

- name: compilation
  cloud_properties:
    instance_type: m4.large
    spot_bid_price: 0.13 # on-demand price: 0.111
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 5_000
      type: gp2
      encrypted: true
    security_groups:
    - <% .VMsSecurityGroupID %>

disk_types:
- name: default
  disk_size: 50_000
  cloud_properties:
    type: gp2
    encrypted: true
- name: large
  disk_size: 200_000
  cloud_properties:
    type: gp2
    encrypted: true

networks:
- name: public
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns:
    - 10.0.0.2
    az: z1
    static:
    - 10.0.0.6
    - 10.0.0.7
    reserved:
    - 10.0.0.1-10.0.0.5
    cloud_properties:
      subnet: <% .PublicSubnetID %>
- name: private
  type: manual
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    dns:
    - 10.0.0.2
    az: z1
    reserved:
    - 10.0.1.1-10.0.1.5
    cloud_properties:
      subnet: <% .PrivateSubnetID %>

- name: vip
  type: vip

vm_extensions:
- name: atc
  cloud_properties:
    security_groups:
    - <% .VMsSecurityGroupID %>
    - <% .ATCSecurityGroupID %>

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: private