---
name: bosh
releases:
- name: bosh
  url: <% .DirectorReleaseURL %>
  sha1: <% .DirectorReleaseSHA1 %>
- name: bosh-aws-cpi
  url: <% .DirectorCPIReleaseURL %>
  sha1: <% .DirectorCPIReleaseSHA1 %>
- name: bpm
  url: <% .DirectorBPMReleaseURL %>
  sha1: <% .DirectorBPMReleaseSHA1 %>

resource_pools:
- name: vms
  network: private
  stemcell:
    url: <% .StemcellURL %>
    sha1: <% .StemcellSHA1 %>
  cloud_properties:
    instance_type: t2.small
    ephemeral_disk:
      size: 25_000
      type: gp2
    availability_zone: <% .AvailabilityZone %>
  env:
    bosh:
      # c1oudc0w is a default password for vcap user
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"

disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties:
    type: gp2

networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns:
    - 10.0.0.2
    cloud_properties:
      subnet: <% .DirectorSubnetID %>
- name: public
  type: vip

jobs:
- name: bosh
  instances: 1
  templates:
  - name: bpm
    release: bpm
  - name: nats
    release: bosh
  - name: director
    release: bosh
  - name: health_monitor
    release: bosh
  - name: registry
    release: bosh
  - name: aws_cpi
    release: bosh-aws-cpi
  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [10.0.0.6]
    default: [dns, gateway]
  - name: public
    static_ips:
    - <% .PublicIP %>

  properties:
    nats:
      address: 10.0.0.6
      user: nats
      password: <% .NATSPassword %>
      tls:
        ca: ((nats_server_tls.ca))
        client_ca:
          certificate: ((nats_ca.certificate))
          private_key: ((nats_ca.private_key))
        server:
          certificate: ((nats_server_tls.certificate))
          private_key: ((nats_server_tls.private_key))
        director:
          certificate: ((nats_clients_director_tls.certificate))
          private_key: ((nats_clients_director_tls.private_key))
        health_monitor:
          certificate: ((nats_clients_health_monitor_tls.certificate))
          private_key: ((nats_clients_health_monitor_tls.private_key))

    postgres: &db
      host: <% .DBHost %>
      user: <% .DBUsername %>
      password: <% .DBPassword %>
      port: <% .DBPort %>
      database: <% .DBName %>
      adapter: postgres

    registry:
      address: 10.0.0.6
      host: 10.0.0.6
      db: *db
      http:
        user: admin
        password: <% .RegistryPassword %>
        port: 25777
      username: admin
      password: <% .RegistryPassword %>
      port: 25777

    blobstore:
      provider: s3
      s3_region: <% .AWSRegion %>
      access_key_id: "<% .S3AWSAccessKeyID %>"
      secret_access_key: "<% .S3AWSSecretAccessKey %>"
      bucket_name: <% .BlobstoreBucket %>

    director:
      address: 127.0.0.1
      name: bosh
      db: *db
      cpi_job: aws_cpi
      max_threads: 10
      user_management:
        provider: local
        local:
          users:
          - name: <% .AdminUserName %>
            password: <% .AdminUserPassword %>
          - name: hm
            password: <% .HMUserPassword %>
      ssl:
        cert: |-
          <% .Indent "10" .DirectorCert %>
        key: |-
          <% .Indent "10" .DirectorKey %>
      trusted_certs: |-
        <% .Indent "8" .DBCACert %>
    hm:
      resurrector_enabled: true
      director_account:
        user: hm
        password: <% .HMUserPassword %>
        ca_cert: |-
          <% .Indent "10" .DirectorCACert %>

    aws: &aws
      access_key_id: "<% .BoshAWSAccessKeyID %>"
      secret_access_key: "<% .BoshAWSSecretAccessKey %>"
      default_key_name: <% .KeyPairName %>
      default_security_groups:
      - <% .BoshSecurityGroupID %>
      - <% .VMsSecurityGroupID %>
      region: <% .AWSRegion %>
    agent:
      mbus: "nats://nats:<% .NATSPassword %>@10.0.0.6:4222"
    ntp: &ntp
    - 0.pool.ntp.org
    - 1.pool.ntp.org

cloud_provider:
  template:
    name: aws_cpi
    release: bosh-aws-cpi
  ssh_tunnel:
    host: <% .PublicIP %>
    port: 22
    user: vcap
    private_key: <% .PrivateKeyPath %>
  mbus: "https://mbus:<% .MbusPassword %>@<% .PublicIP %>:6868"
  properties:
    aws: *aws
    agent:
      mbus: "https://mbus:<% .MbusPassword %>@0.0.0.0:6868"
    blobstore:
      provider: local
      path: /var/vcap/micro_bosh/data/cache
    ntp: *ntp

variables:
- name: nats_ca
  type: certificate
  options:
    is_ca: true
    common_name: default.nats-ca.bosh-internal

- name: nats_server_tls
  type: certificate
  options:
    ca: nats_ca
    common_name: default.nats.bosh-internal
    alternative_names: [10.0.0.6]
    extended_key_usage:
    - server_auth

- name: nats_clients_director_tls
  type: certificate
  options:
    ca: nats_ca
    common_name: default.director.bosh-internal
    extended_key_usage:
    - client_auth

- name: nats_clients_health_monitor_tls
  type: certificate
  options:
    ca: nats_ca
    common_name: default.hm.bosh-internal
    extended_key_usage:
    - client_auth